version: 2
jobs:
  build:
    docker:
    - image: circleci/elixir:1.6.5
    working_directory: ~/99-Elixir-Problems
    steps:
      - checkout
      - run: mix test

workflows:
  version: 2
  full_cycle:
    jobs:
      - build
