version: 2
jobs:
  build:
    docker:
    - image: circleci/elixir:1.8.1
    working_directory: ~/99-Elixir-Problems
    steps:
      - checkout
      - run:
          name: "Init ..."
          command: mix local.hex --force
      - run:
          name: "Get dependencies ..."
          command: mix deps.get
      - run:
          name: "Run dialyzer ..."
          command: mix dialyzer
      - run:
          name: "Run test(s) ..."
          command: mix test

workflows:
  version: 2
  full_cycle:
    jobs:
      - build
